# ----
# Site

title: Tan's Blog
url: ""
baseurl: /story
google_analytics_key: UA-132756645-1
disqus_shortname: congto
newsletter_action:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Trang blog của dịch vụ cloud365.vn.
author: 
  name: 
  email: 
  twitter: # twitter username without the @ symbol
social:
  name: cloud365.vn
  links:
    - http://blogcloud365vn.github.io/

# -----
# Build

timezone: Etc/UTC

permalink: /:categories/:title/
paginate: 8
link-tags: true

plugins:
  - jekyll-paginate
  - jekyll-extract-element
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-archives
  - jekyll-gist
  - jekyll-timeago
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  sets:


jekyll-archives:
  enabled: ['categories']

jekyll_timeago:
  depth: 2
  translations_path: '/_data/timeago_locale/*.yaml'
  default_locale: 'vi'
  fallbacks: true
  available_locales:
    - 'en'
    - 'es'
    - 'fr'

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      comments: true
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      comments: true
  -
    scope:
      type: "sets"
    values:
      _hide_content: true
  -
    scope:
      path: "index.html"
    values:
      body_class: "show_hero_search"
  -
    scope:
      path: "404.html"
    values:
      layout: "404layout"
    
# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - Email
  - RSS

types:
  - Document
  - Video

_comments:
